# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(704, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 11, 682, 378))
        self.label.setStyleSheet("border-image: url(:/BgImg/Desktop/BgForSplashScreen.jpg);\n"
"border-radius:10px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 682, 378))
        self.label_2.setStyleSheet("background:rgba(20,20,20,120);\n"
"border-radius:10px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setGeometry(QtCore.QRect(10, 0, 682, 378))
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"color:rgb(220,220,220);\n"
"border-radius:10px;\n"
"background:none;\n"
"\n"
"}\n"
"")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.Title = QtWidgets.QLabel(self.dropShadowFrame)
        self.Title.setGeometry(QtCore.QRect(0, 49, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color:  rgb(140, 100, 200);\n"
"")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.Discription = QtWidgets.QLabel(self.dropShadowFrame)
        self.Discription.setGeometry(QtCore.QRect(0, 130, 681, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.Discription.setFont(font)
        self.Discription.setStyleSheet("color: rgb(140, 100, 200);")
        self.Discription.setAlignment(QtCore.Qt.AlignCenter)
        self.Discription.setObjectName("Discription")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(44, 275, 591, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(200,120,220);\n"
"border-style:none;\n"
"border-radius:10px;\n"
"text-align:center;\n"
"color:#FFF;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.443, x2:1, y2:0.454545, stop:0.288557 rgba(136, 68, 204, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.Loading.setGeometry(QtCore.QRect(0, 300, 681, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.Loading.setFont(font)
        self.Loading.setStyleSheet("color:  rgb(140, 100, 200);\n"
"")
        self.Loading.setAlignment(QtCore.Qt.AlignCenter)
        self.Loading.setObjectName("Loading")
        self.CopyRight = QtWidgets.QLabel(self.dropShadowFrame)
        self.CopyRight.setGeometry(QtCore.QRect(0, 345, 671, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.CopyRight.setFont(font)
        self.CopyRight.setStyleSheet("color: rgb(140, 100, 200);")
        self.CopyRight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CopyRight.setObjectName("CopyRight")
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.Title.setText(_translate("SplashScreen", "<strong>ΔLITΔ</strong>"))
        self.Discription.setText(_translate("SplashScreen", "Your Personal <strong>Virtual Assistant</strong>"))
        self.Loading.setText(_translate("SplashScreen", "Loading.."))
        self.CopyRight.setText(_translate("SplashScreen", "<strong>Created by</strong> Team ELITE"))
import splashScreenBg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
